/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_binome_musictouch_Player */

#ifndef _Included_com_binome_musictouch_Player
#define _Included_com_binome_musictouch_Player
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_binome_musictouch_Player
 * Method:    play
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_binome_musictouch_Player_play
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_binome_musictouch_Player
 * Method:    setTempo
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_binome_musictouch_Player_setTempo
  (JNIEnv *, jobject, jfloat);

#ifdef __cplusplus
}
#endif
#endif
